# Generated by Django 5.0.4 on 2024-04-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetegory',
            new_name='Category',
        ),
    ]
